<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Automation</title>
</head>
<body>
  <h1>Networking and System Administration Project</h1>
  <h2>hello world</h2>
  <p>This is Pavani Pedineedi CA 1 </p>
</body>
</html>
